// 词库：以后想扩充，直接往这个数组里加 { word: "xxx", meaning: "xxx" } 就行
// 也可以以后拆成多个词表文件，按词表名切换
const WORDS = [
  { word: "abandon", meaning: "v. 放弃；遗弃" },
  { word: "ability", meaning: "n. 能力；才能" },
  { word: "absorb", meaning: "v. 吸收；吸引" },
  { word: "abstract", meaning: "adj. 抽象的" },
  { word: "academic", meaning: "adj. 学术的；学院的" },
  { word: "accept", meaning: "v. 接受；同意" },
  { word: "access", meaning: "n. 通道；访问 v. 访问" },
  { word: "accident", meaning: "n. 事故；意外" },
  { word: "account", meaning: "n. 账户；解释" },
  { word: "achieve", meaning: "v. 实现；达到" },
  { word: "acquire", meaning: "v. 获得；习得" },
  { word: "adapt", meaning: "v. 适应；改编" },
  { word: "addition", meaning: "n. 增加；加法" },
  { word: "adequate", meaning: "adj. 足够的；适当的" },
  { word: "adjust", meaning: "v. 调整；适应" },
  { word: "administration", meaning: "n. 管理；行政" },
  { word: "admire", meaning: "v. 钦佩；欣赏" },
  { word: "admit", meaning: "v. 承认；准许进入" },
  { word: "adopt", meaning: "v. 采用；收养" },
  { word: "advance", meaning: "v./n. 前进；进展" },
  { word: "advantage", meaning: "n. 优势；好处" },
  { word: "adventure", meaning: "n. 冒险" },
  { word: "advertise", meaning: "v. 做广告" },
  { word: "advice", meaning: "n. 建议" },
  { word: "advocate", meaning: "v. 提倡 n. 拥护者" },
  { word: "affect", meaning: "v. 影响；感动" },
  { word: "afford", meaning: "v. 负担得起" },
  { word: "agency", meaning: "n. 代理机构" },
  { word: "agenda", meaning: "n. 议程" },
  { word: "aggressive", meaning: "adj. 侵略性的；有进取心的" },
  { word: "agriculture", meaning: "n. 农业" },
  { word: "aim", meaning: "n./v. 目标；瞄准" },
  { word: "alarm", meaning: "n. 警报 v. 使惊恐" },
  { word: "alternative", meaning: "n. 替代品 adj. 可选择的" },
  { word: "ambition", meaning: "n. 雄心；抱负" },
  { word: "amount", meaning: "n. 数量" },
  { word: "analyze", meaning: "v. 分析" },
  { word: "ancient", meaning: "adj. 古代的" },
  { word: "announce", meaning: "v. 宣布" },
  { word: "annual", meaning: "adj. 每年的" },
  { word: "anxious", meaning: "adj. 焦虑的" },
  { word: "apologize", meaning: "v. 道歉" },
  { word: "apparent", meaning: "adj. 明显的" },
  { word: "appeal", meaning: "v./n. 呼吁；吸引；上诉" },
  { word: "appearance", meaning: "n. 外貌；出现" },
  { word: "apply", meaning: "v. 申请；应用" },
  { word: "appoint", meaning: "v. 任命；约定" },
  { word: "appreciate", meaning: "v. 欣赏；感激" },
  { word: "approach", meaning: "v. 接近 n. 方法" },
  { word: "appropriate", meaning: "adj. 适当的" },
  { word: "approve", meaning: "v. 批准；赞成" },
  { word: "arrange", meaning: "v. 安排" },
  { word: "arrest", meaning: "v./n. 逮捕" },
  { word: "artificial", meaning: "adj. 人工的" },
  { word: "ashamed", meaning: "adj. 羞愧的" },
  { word: "aspect", meaning: "n. 方面" },
  { word: "assess", meaning: "v. 评估" },
  { word: "assist", meaning: "v. 协助" },
  { word: "assume", meaning: "v. 假设；承担" },
  { word: "attach", meaning: "v. 附加；使附属" },
  { word: "attend", meaning: "v. 出席；照料" },
  { word: "attitude", meaning: "n. 态度" },
  { word: "attract", meaning: "v. 吸引" },
  { word: "authority", meaning: "n. 权威；当局" },
  { word: "available", meaning: "adj. 可用的；有空的" },
  { word: "average", meaning: "adj. 平均的 n. 平均" },
  { word: "avoid", meaning: "v. 避免" },
  { word: "award", meaning: "n. 奖品 v. 授予" },
  { word: "aware", meaning: "adj. 意识到的" },
  { word: "background", meaning: "n. 背景" },
  { word: "balance", meaning: "n./v. 平衡" },
  { word: "barrier", meaning: "n. 障碍" },
  { word: "behave", meaning: "v. 表现；举止" },
  { word: "belief", meaning: "n. 信念" },
  { word: "benefit", meaning: "n./v. 利益；受益" },
  { word: "bias", meaning: "n. 偏见" },
  { word: "blame", meaning: "v./n. 责备" },
  { word: "bond", meaning: "n. 纽带；债券" },
  { word: "bonus", meaning: "n. 奖金；红利" },
  { word: "boundary", meaning: "n. 边界" },
  { word: "brand", meaning: "n. 品牌" },
  { word: "brief", meaning: "adj. 简短的" },
  { word: "budget", meaning: "n. 预算" },
  { word: "burden", meaning: "n. 负担" },
  { word: "calculate", meaning: "v. 计算" },
  { word: "campaign", meaning: "n. 运动；战役" },
  { word: "cancel", meaning: "v. 取消" },
  { word: "candidate", meaning: "n. 候选人" },
  { word: "capable", meaning: "adj. 有能力的" },
  { word: "capacity", meaning: "n. 容量；能力" },
  { word: "capture", meaning: "v. 捕获；捕捉" },
  { word: "career", meaning: "n. 职业" },
  { word: "cause", meaning: "n. 原因；事业 v. 引起" },
  { word: "challenge", meaning: "n./v. 挑战" },
  { word: "channel", meaning: "n. 频道；渠道" },
  { word: "chapter", meaning: "n. 章节" },
  { word: "character", meaning: "n. 性格；角色；字符" },
  { word: "charge", meaning: "v. 收费；充电；指控 n. 费用" },
  { word: "chase", meaning: "v. 追逐" },
  { word: "circumstance", meaning: "n. 环境；情况" },
  { word: "claim", meaning: "v./n. 声称；索赔" },
  { word: "classic", meaning: "adj. 经典的" },
  { word: "climate", meaning: "n. 气候" },
  { word: "collaborate", meaning: "v. 合作" },
  { word: "collapse", meaning: "v./n. 倒塌；崩溃" },
  { word: "colleague", meaning: "n. 同事" },
  { word: "combine", meaning: "v. 结合" },
  { word: "comfort", meaning: "n./v. 舒适；安慰" },
  { word: "command", meaning: "v./n. 命令" },
  { word: "comment", meaning: "n./v. 评论" },
  { word: "commercial", meaning: "adj. 商业的" },
  { word: "commit", meaning: "v. 承诺；犯（罪）" },
  { word: "communicate", meaning: "v. 交流" },
  { word: "community", meaning: "n. 社区" },
  { word: "compare", meaning: "v. 比较" },
  { word: "compete", meaning: "v. 竞争" },
  { word: "complex", meaning: "adj. 复杂的 n. 综合体" },
  { word: "component", meaning: "n. 组成部分" },
  { word: "concept", meaning: "n. 概念" },
  { word: "concern", meaning: "n./v. 关心；担忧" },
  { word: "conclude", meaning: "v. 得出结论" },
  { word: "conduct", meaning: "v. 进行；引导 n. 行为" },
  { word: "confidence", meaning: "n. 信心" },
  { word: "confirm", meaning: "v. 确认" },
  { word: "conflict", meaning: "n./v. 冲突" },
  { word: "conscious", meaning: "adj. 有意识的" },
  { word: "consequence", meaning: "n. 后果" },
  { word: "consider", meaning: "v. 考虑" },
  { word: "consist", meaning: "v. 组成" },
  { word: "constant", meaning: "adj. 持续的；不变的" },
  { word: "construct", meaning: "v. 建造" },
  { word: "consume", meaning: "v. 消耗；消费" },
  { word: "contact", meaning: "v./n. 联系" },
  { word: "contain", meaning: "v. 包含" },
  { word: "contemporary", meaning: "adj. 当代的" },
  { word: "content", meaning: "n. 内容 adj. 满足的" },
  { word: "context", meaning: "n. 上下文；背景" },
  { word: "contribute", meaning: "v. 贡献；促成" },
  { word: "convenient", meaning: "adj. 方便的" },
  { word: "conventional", meaning: "adj. 传统的；常规的" },
  { word: "convince", meaning: "v. 说服" },
  { word: "cooperate", meaning: "v. 合作" },
  { word: "cope", meaning: "v. 应对" },
  { word: "core", meaning: "n. 核心" },
  { word: "corporate", meaning: "adj. 公司的" },
  { word: "correspond", meaning: "v. 符合；通信" },
  { word: "cost", meaning: "n. 成本 v. 花费" },
  { word: "council", meaning: "n. 理事会；委员会" },
  { word: "counter", meaning: "n. 柜台 v. 反驳" },
  { word: "create", meaning: "v. 创造" },
  { word: "credit", meaning: "n. 信用；学分 v. 归功于" },
  { word: "crisis", meaning: "n. 危机" },
  { word: "criterion", meaning: "n. 标准" },
  { word: "critical", meaning: "adj. 批评的；关键的" },
  { word: "culture", meaning: "n. 文化" },
  { word: "curious", meaning: "adj. 好奇的" },
  { word: "current", meaning: "adj. 当前的 n. 电流；潮流" },
  { word: "damage", meaning: "n./v. 损害" },
  { word: "debate", meaning: "n./v. 辩论" },
  { word: "decade", meaning: "n. 十年" },
  { word: "decide", meaning: "v. 决定" },
  { word: "declare", meaning: "v. 宣布；申报" },
  { word: "decline", meaning: "v./n. 下降；拒绝" },
  { word: "dedicate", meaning: "v. 奉献；致力于" },
  { word: "define", meaning: "v. 定义" },
  { word: "deliver", meaning: "v. 递送；交付" },
  { word: "demand", meaning: "n./v. 需求；要求" },
  { word: "demonstrate", meaning: "v. 证明；演示" },
  { word: "deny", meaning: "v. 否认" },
  { word: "depend", meaning: "v. 依赖" },
  { word: "depress", meaning: "v. 使沮丧" },
  { word: "derive", meaning: "v. 获得；起源" },
  { word: "describe", meaning: "v. 描述" },
  { word: "deserve", meaning: "v. 值得" },
  { word: "design", meaning: "v./n. 设计" },
  { word: "desire", meaning: "n./v. 渴望" },
  { word: "despite", meaning: "prep. 尽管" },
  { word: "detect", meaning: "v. 察觉；探测" },
  { word: "determine", meaning: "v. 决定；确定" },
  { word: "develop", meaning: "v. 发展；开发" },
  { word: "devote", meaning: "v. 致力于" },
  { word: "diet", meaning: "n. 饮食" },
  { word: "differ", meaning: "v. 不同" },
  { word: "digital", meaning: "adj. 数字的" },
  { word: "dilemma", meaning: "n. 困境" },
  { word: "dimension", meaning: "n. 维度；尺寸" },
  { word: "diminish", meaning: "v. 减少" },
  { word: "direct", meaning: "adj. 直接的 v. 指导" },
  { word: "discipline", meaning: "n. 纪律；学科" },
  { word: "discount", meaning: "n. 折扣" },
  { word: "discover", meaning: "v. 发现" },
  { word: "discriminate", meaning: "v. 歧视；区别" },
  { word: "display", meaning: "v./n. 展示" },
  { word: "dispose", meaning: "v. 处理；处置" },
  { word: "distance", meaning: "n. 距离" },
  { word: "distinct", meaning: "adj. 明显的；不同的" },
  { word: "distinguish", meaning: "v. 区分" },
  { word: "distribute", meaning: "v. 分配；分发" },
  { word: "disturb", meaning: "v. 打扰" },
  { word: "diverse", meaning: "adj. 多样的" },
  { word: "document", meaning: "n. 文件 v. 记录" },
  { word: "domestic", meaning: "adj. 国内的；家庭的" },
  { word: "dominate", meaning: "v. 主导" },
  { word: "draft", meaning: "n. 草稿 v. 起草" },
  { word: "drama", meaning: "n. 戏剧" },
  { word: "effort", meaning: "n. 努力" },
  { word: "elaborate", meaning: "adj. 精心的 v. 详细说明" },
  { word: "emerge", meaning: "v. 出现" },
  { word: "emphasize", meaning: "v. 强调" },
  { word: "employ", meaning: "v. 雇用；使用" },
  { word: "enable", meaning: "v. 使能够" },
  { word: "encounter", meaning: "v./n. 遭遇" },
  { word: "encourage", meaning: "v. 鼓励" },
  { word: "endure", meaning: "v. 忍受" },
  { word: "enforce", meaning: "v. 执行；强制" },
  { word: "enhance", meaning: "v. 增强" },
  { word: "enormous", meaning: "adj. 巨大的" },
  { word: "ensure", meaning: "v. 确保" },
  { word: "enter", meaning: "v. 进入" },
  { word: "establish", meaning: "v. 建立" },
  { word: "estimate", meaning: "v./n. 估计" },
  { word: "evaluate", meaning: "v. 评估" },
  { word: "evidence", meaning: "n. 证据" },
  { word: "evolve", meaning: "v. 进化" },
  { word: "exceed", meaning: "v. 超过" },
  { word: "exchange", meaning: "v./n. 交换" },
  { word: "exclude", meaning: "v. 排除" },
  { word: "exhibit", meaning: "v. 展览 n. 展品" },
  { word: "exist", meaning: "v. 存在" },
  { word: "expand", meaning: "v. 扩大" },
  { word: "expense", meaning: "n. 费用" },
  { word: "experiment", meaning: "n./v. 实验" },
  { word: "expert", meaning: "n. 专家" },
  { word: "explain", meaning: "v. 解释" },
  { word: "explore", meaning: "v. 探索" },
  { word: "expose", meaning: "v. 暴露；揭露" },
  { word: "extend", meaning: "v. 延伸" },
  { word: "external", meaning: "adj. 外部的" },
  { word: "facilitate", meaning: "v. 促进" },
  { word: "factor", meaning: "n. 因素" },
  { word: "fail", meaning: "v. 失败" },
  { word: "familiar", meaning: "adj. 熟悉的" },
  { word: "fashion", meaning: "n. 时尚" },
  { word: "feature", meaning: "n. 特征；特写 v. 以…为特色" },
  { word: "federal", meaning: "adj. 联邦的" },
  { word: "figure", meaning: "n. 数字；人物；身材 v. 认为" },
  { word: "finance", meaning: "n. 金融 v. 提供资金" },
  { word: "flexible", meaning: "adj. 灵活的" },
  { word: "focus", meaning: "v./n. 聚焦；焦点" },
  { word: "force", meaning: "n. 力量 v. 强迫" },
  { word: "former", meaning: "adj. 以前的" },
  { word: "foundation", meaning: "n. 基础；基金会" },
  { word: "frame", meaning: "n. 框架 v. 陷害" },
  { word: "frequent", meaning: "adj. 频繁的" },
  { word: "function", meaning: "n. 功能 v. 运转" },
  { word: "fundamental", meaning: "adj. 基本的" },
  { word: "further", meaning: "adj./adv. 进一步" },
  { word: "generate", meaning: "v. 产生" },
  { word: "genuine", meaning: "adj. 真正的" },
  { word: "global", meaning: "adj. 全球的" },
  { word: "govern", meaning: "v. 治理" },
  { word: "gradual", meaning: "adj. 逐渐的" },
  { word: "grant", meaning: "v. 授予 n. 拨款" },
  { word: "guarantee", meaning: "v./n. 保证" },
  { word: "handle", meaning: "v. 处理 n. 把手" },
  { word: "harm", meaning: "n./v. 伤害" },
  { word: "hence", meaning: "adv. 因此" },
  { word: "hierarchy", meaning: "n. 等级制度" },
  { word: "highlight", meaning: "v. 强调 n. 亮点" },
  { word: "horizon", meaning: "n. 地平线；视野" },
  { word: "identify", meaning: "v. 识别" },
  { word: "ignore", meaning: "v. 忽视" },
  { word: "illustrate", meaning: "v. 说明；图解" },
  { word: "imagine", meaning: "v. 想象" },
  { word: "immediate", meaning: "adj. 立即的" },
  { word: "impact", meaning: "n./v. 影响；冲击" },
  { word: "implement", meaning: "v. 实施 n. 工具" },
  { word: "imply", meaning: "v. 暗示" },
  { word: "impose", meaning: "v. 强加" },
  { word: "improve", meaning: "v. 改进" },
  { word: "incident", meaning: "n. 事件" },
  { word: "indicate", meaning: "v. 表明" },
  { word: "individual", meaning: "adj. 个人的 n. 个人" },
  { word: "industry", meaning: "n. 工业；行业" },
  { word: "influence", meaning: "n./v. 影响" },
  { word: "inform", meaning: "v. 通知" },
  { word: "initial", meaning: "adj. 最初的" },
  { word: "initiative", meaning: "n. 主动性；倡议" },
  { word: "injury", meaning: "n. 伤害" },
  { word: "innovate", meaning: "v. 创新" },
  { word: "inspire", meaning: "v. 激励；启发" },
  { word: "install", meaning: "v. 安装" },
  { word: "instance", meaning: "n. 例子" },
  { word: "institution", meaning: "n. 机构" },
  { word: "instruct", meaning: "v. 指导；指示" },
  { word: "insurance", meaning: "n. 保险" },
  { word: "integrate", meaning: "v. 整合" },
  { word: "intellectual", meaning: "adj. 智力的 n. 知识分子" },
  { word: "intelligent", meaning: "adj. 聪明的" },
  { word: "intense", meaning: "adj. 强烈的" }
];
